absolute_urls: false

home:
  alias: '/home'

pages:
  theme: semanticui
  markdown_extra: false
  process:
    markdown: true
    twig: false

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: false
  css_rewrite: false
  js_pipeline: false
  js_minify: false

errors:
  display: true
  log: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true

plugins:
  highlight:
    theme: solarized_dark
